// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsXrFC6Jn3h_5OFb_kXAZ8C7po1BLvDmU',
    appId: '1:337131147053:web:0f392b02758eb593ee4da4',
    messagingSenderId: '337131147053',
    projectId: 'hackathon-3a31c',
    authDomain: 'hackathon-3a31c.firebaseapp.com',
    storageBucket: 'hackathon-3a31c.appspot.com',
    measurementId: 'G-ZXE9XS9DG0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvGkcACbcSq-jJFXNQPxczNGr-MsITip8',
    appId: '1:337131147053:android:f50860d696564e77ee4da4',
    messagingSenderId: '337131147053',
    projectId: 'hackathon-3a31c',
    storageBucket: 'hackathon-3a31c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCerlV1UU-5FkyAAB7nZg-OVMSP_KKWjas',
    appId: '1:337131147053:ios:d750fb8c7cbab28dee4da4',
    messagingSenderId: '337131147053',
    projectId: 'hackathon-3a31c',
    storageBucket: 'hackathon-3a31c.appspot.com',
    iosBundleId: 'com.example.pawfect',
  );
}
